name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'
    - name: checkout
      uses: actions/checkout@v2
    - name: install dependencies
      run: go mod download
    - name: tests
      env:
        GO111MODULE: on
      run: make test-all
    - name: coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: cd /tmp && go get github.com/mattn/goveralls && cd - && goveralls -coverprofile=covprofile.out -service=github-actions -repotoken=$COVERALLS_TOKEN